version: '3.9'

services:
  app:
    restart: always
    build:
      context: .
    ports:
      - 8000:8000
  db:
    image: postgres:13
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    ports:
      - 5432:5432
    expose:
      - 5432
    
